### ISSUE TITLE
Combined .diy files

### ISSUE THREAD

**Issue by EL34xyz** [colganr/steel-string-singer-sn-002#1]
I think combining all the boards into two files would make it easier for people to add them to my shopping cart.
My CNC fixture that holds the board material has a max board length of 21 inches. 
I combined all the boards into two files that are around 16 inches long.
I used cut lines so I know where to cut apart the boards.
Here's what the two files look like in DIYLC
The two .diy files are in the zip file under the image below

![SteelStringSlinger](https://user-images.githubusercontent.com/16766383/60518299-3f7edf80-9caf-11e9-98f0-3ce814a4a8e9.png)

[SteelStringSlinger2.zip](https://github.com/colganr/steel-string-singer-sn-002/files/3364733/SteelStringSlinger2.zip)

**Comment by EL34xyz** [comment]
If you want to have the boards made, go to the Hoffmanamps analyzer program here to add them to your shopping cart.
https://hoffmanamps.com/php/DIYLC/DiyFileAnalyzer.php

**Comment by EL34xyz** [comment]
Here's the github page for DIYLC where it can be downloaded
https://github.com/bancika/diy-layout-creator/releases/tag/v3.57.0a

**Comment by EL34xyz** [comment]
Here's a couple pdf files showing what the two boards look like in DIYLC

[SteelStringSlinger1.pdf](https://github.com/colganr/steel-string-singer-sn-002/files/3364734/SteelStringSlinger1.pdf)
[SteelStringSlinger2.pdf](https://github.com/colganr/steel-string-singer-sn-002/files/3364735/SteelStringSlinger2.pdf)

**Comment by EL34xyz** [comment]
I added a new catalog page to my web store to make it way easier to order Ryan's board set
Go to this page to order the Steel String Slinger board set
https://hoffmanamps.com/MyStore/catalog/MiscEyeletBoard.htm

**Comment by colganr** [comment]
@EL34xyz I updated my ReadMe and included links to https://hoffmanamps.com/MyStore/catalog/MiscEyeletBoard.htm Thank you for kindly hosting the files. I also added your two combined board files to my "upload to Hoffman Amplifiers" page for future reference. This will make it a lot easier for the future builders.

**Comment by EL34xyz** [comment]
Thanks Ryan
