### ISSUE TITLE
Clarify FET board in note

### ISSUE THREAD

**Issue by timrobertson100** [colganr/steel-string-singer-sn-002#5]
HI @colganr 

On the FET board, I notice the labelling on the PCB for resistor values differ from the eyelet board diagram.
I recall seeing somewhere a comment on a thread about different editions of FET but can't find it again.

It would be good to update the layout to match or put a note about this.

I am using the PCB printed values - please can you comment if this is not advisable?

Thanks

**Comment by ronvdlaak** [comment]
Print values are ok Tim. You might have to bias if you are unlucky. i had 4 on stock.....3 out of 4 were ok with pcb resistor value. 1 couldnt even reach unity gain. 

Procedure can be found on ampgarage. If you ever build yr own fuzz pedal you know how this works..



Verstuurd vanaf mijn iPhone

**Comment by timrobertson100** [comment]
Thanks @ronvdlaak

For anyone stumbling on this, please see [this thread](https://ampgarage.com/forum/viewtopic.php?f=5&t=18389) which has a PDF showing how to use batteries to check bias before installing the FET board.
